version: '3.7'
services: 
  backend:
    container_name: flask-container
    build: .
    volumes: 
      - .:/opt/app
    env_file: .env
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 main.py'
    depends_on:
      - db
  db:
    build: ./db
    container_name: flask-db-container
    env_file: .env
